spring:
  application:
    name: 'EcoDom'
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    driverClassName: org.postgresql.Driver
    username: clinic
    password: admin
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-m37m1ey1svnrduyu.us.auth0.com/
          audiences:  https://ecodom-auth
      client:
        registration:
          github:
            client-id: OAUTH_CLIENT_REGISTRATION_GITHUB_CLIENT-ID
            client-secret: OAUTH_CLIENT_REGISTRATION_GITHUB_CLIENT-SECRET
            scope: read:user
          google:
            client-id: OAUTH_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID
            client-secret: OAUTH_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET
            scope:
              - openid
              - profile
              - email
server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
frontend:
  url: http://localhost:3000
external:
  tariff:
    api:
      base-url: https://energy-instrat-api.azurewebsites.net/api/prices/energy_price_rdn_hourly?
secrets:
  jwt:
    key: ${SECRETS_JWT_KEY}
    expirationMs: 172800000
#    #h2
#    spring.jpa.properties.hibernate.hbm2ddl.auto = create
#    spring.datasource.url=jdbc:h2:mem:./plusmed_db
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.h2.console.enabled=true
#    spring.h2.console.path=/h2-console
#
#    # listening on localhost only
#    server.address=127.0.0.1
#    server.port=8081
