version: '3.8'  # Specify the version of Docker Compose

services:
  postgres_db:  # Name of the service
    image: postgres:latest  # Use the official PostgreSQL image
    container_name: eclinic-db  # Name of the container
    environment:
      POSTGRES_USER: clinic  # Set the PostgreSQL username
      POSTGRES_PASSWORD: admin  # Set the PostgreSQL password
      POSTGRES_DB: dev  # Set the name of the default database
    ports:
      - "5432:5432"  # Map the container's port 5432 to the host's port 5454
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist the PostgreSQL data
    healthcheck:
      test: ["CMD", "pg_isready", "--username=clinic", "--dbname=dev"]
      timeout: 5s
      retries: 5
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      SECRETS_JWT_KEY: secret
      POSTGRES_URL: postgres_db:5432
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local  # Use a local driver to persist data